### ISSUE TITLE
Wrong counting in readme

### ISSUE THREAD

**Issue by AlexeyPetroff** [pawel-lewtak/coding-dojo-template-python#2]
In readme You say:

For example, how much does this basket of books cost?
* 2 copies of the first book
* 2 copies of the second book
* 2 copies of the third book
* 1 copy of the fourth book
* 1 copy of the fifth book
(answer: 51.20 EUR)

That mean that user bought one full set(5 books) and one 3-books set
First 5-book set:
5 * €8 * 0.75(25% discount) = €30
Second set:
3 * €8 * 0.9(10% discount) = €21,6

Price: 30+21.6 = €51.6, not 51.2

**Comment by pawel-lewtak** [comment]
Thanks for pointing that out! Clue to solving this is one of last sentence of the description:

> Your mission is to write a piece of code to calculate the price of any conceivable shopping basket, giving as big a discount as possible.

That being said, biggest discount would be if we assumed two sets each consisting of four books (1,2,3,4 and 1,2,3,5):
2 * (4 * €8 * 0.8 (20% discount)) = €51.2

Don't worry, that's a common question :-)

**Comment by pawel-lewtak** [comment]
I will update the description to clarify it a bit for next workshops. Thanks!
